### ISSUE TITLE
Can't get global variables in a thread.

### ISSUE THREAD

**Issue by daa233** [daa233/easy-ecard#1]
source code: (In a new Thread)
final HttpClientData httpClientData = (HttpClientData) getApplication();
                            httpClientData.setHttpClient(httpClient);
                            if (httpClientData.getHttpClient() != null) {
                                Log.d("httpClient", "success to spread");
                            }
LodCat
12-17 23:07:45.301: W/System.err(4306): java.lang.ClassCastException: android.app.Application cannot be cast to com.duang.easyecard.GlobalData.HttpClientData
12-17 23:07:45.301: W/System.err(4306):     at com.duang.easyecard.Activities.SigninActivity$3.run(SigninActivity.java:252)
12-17 23:07:45.301: W/System.err(4306):     at java.lang.Thread.run(Thread.java:856)
12-17 23:09:24.765: W/ThrottleService(399): unable to find stats for iface rmnet0

**Comment by daa233** [comment]
I solved the problem yesterday. There are supposed to be only one application. (seems to be so)
But I put another application called "UrlConstant" there. It only has some static constants.
